services:
  web:
    image: ${DOCKERHUB_USER:-local}/taskpilot-frontend:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile.web

  space:
    image: ${DOCKERHUB_USER:-local}/taskpilot-space:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/space/Dockerfile.space

  admin:
    image: ${DOCKERHUB_USER:-local}/taskpilot-admin:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/admin/Dockerfile.admin

  live:
    image: ${DOCKERHUB_USER:-local}/taskpilot-live:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/live/Dockerfile.live

  api:
    image: ${DOCKERHUB_USER:-local}/taskpilot-backend:${APP_RELEASE:-latest}
    build:
      context: ../../apps/api
      dockerfile: Dockerfile.api

  proxy:
    image: ${DOCKERHUB_USER:-local}/taskpilot-proxy:${APP_RELEASE:-latest}
    build:
      context: ../../apps/proxy
      dockerfile: Dockerfile.ce
