# Copyright (c) 2023-present TaskPilot Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.15

from django.db import migrations


class Migration(migrations.Migration):
    """Rejoin the two 0121 branches.

    The fork's issue_external_src_id_idx and upstream's alter_estimate_type
    both numbered themselves 0121 off 0120, leaving the graph with two leaves.
    This node carries no operations of its own; it only reunites the branches.
    """

    dependencies = [
        ("db", "0121_issue_external_src_id_idx"),
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
    ]

    operations = []
